telemetry = false

[install]
# Only install package versions published at least 7 days ago
minimumReleaseAge = 604800 # seconds
ignoreScripts = true
exact = true
cache = true
optional = true
frozenLockfile = true

[install.lockfile]
save = true

[run]
target = "node"
